# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: todoapp
          POSTGRES_DB: todos
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo apt-get update
      - run: sleep 30
      - run: |
          psql \
          -d $TEST_DATABASE_URL \
          -c "CREATE TABLE todos (name char(25));"
      - run: npm install
      - run: pwd
      - run: npm run migrate
      - run: npm test
